<?xml version="1.0" encoding="utf-8"?><Database Name="ABC_Car_Traders" Class="ABCDataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-MPDGLCC\SQLEXPRESS;Initial Catalog=ABC_Car_Traders;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="ABC_Car_TradersConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.car" Member="cars">
    <Type Name="car">
      <Column Name="car_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="car_make" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="car_model" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="car_year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="car_price" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="car_desc" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="car_stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="car_image" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="uid" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="is_admin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="user_customer" Member="customer" ThisKey="uid" OtherKey="customer_id" Type="customer" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.car_part" Member="car_parts">
    <Type Name="car_part">
      <Column Name="part_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="part_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="part_desc" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="part_image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="part_stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="part_price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="customer_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="dob" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="contact" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="customer_order" Member="orders" ThisKey="customer_id" OtherKey="customer_id" Type="order" />
      <Association Name="user_customer" Member="user" ThisKey="customer_id" OtherKey="uid" Type="user" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[order]" Member="orders">
    <Type Name="order">
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customer_id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="shipping_add" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="order_desc" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ship_to" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="payment_status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="order_status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="order_type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="customer_order" Member="customer" ThisKey="customer_id" OtherKey="customer_id" Type="customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sales" Member="sales">
    <Type Name="sale">
      <Column Name="sale_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sale_type" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="sale_desc" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="unit_price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sale_quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total_amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.revenue" Member="revenues">
    <Type Name="revenue">
      <Column Name="year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="month" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cars" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="car_parts" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>